x-common-timezone: &services-timezone Etc/UTC

name: local_cubesql
services:
  cubesql-server:
#   This image is only available for Linux x86-64
#   Set platform to run it in emulation mode on hosts which support that platform
    platform: linux/amd64
    container_name: cubesql
    hostname: cubesql
    image: jotools/cubesql:5.9.1
    environment:
      TZ: *services-timezone
    volumes:
      - cubesql_data:/data
    networks:
      - local_cubesql_net
    ports:
      - 4430:4430
    restart: unless-stopped
  cubesql-webadmin:
    container_name: cubesql-webadmin
    hostname: cubesql-webadmin
    image: jotools/cubesql-webadmin
    environment:
      TZ: *services-timezone
      CUBESQL_HOSTNAME: host.docker.internal
      CUBESQL_PORT: 4430
      CUBESQL_USERNAME: admin
      CUBESQL_PASSWORD: admin
      CUBESQL_CONNECTIONCHOICE: /data/connection-choice.json
    volumes:
      - ./connection-choice.json:/data/connection-choice.json
    networks:
      - local_cubesql_net
    ports:
      - 4431:80
    restart: unless-stopped
    depends_on:
      - cubesql-server

volumes:
  cubesql_data:
    driver: local
    name: cubesql_data

networks:
  local_cubesql_net:
    name: local_cubesql
